#!/bin/bash

function fixcfg()
{
	cfg=$OPENSHIFT_DATA_DIR/victims-web/src/victims_web/application.cfg
	sed -i s/'^DEBUG = True$'/'DEBUG = False'/g "$cfg"
	sed -i s/'MONGODB_PORT = os.environ.*'/"MONGODB_PORT = int(os.environ['OPENSHIFT_DB_PORT'])"/ "$cfg"
}

if [ ! -d $OPENSHIFT_REPO_DIR/libs/victims_web ]; then
	if [ ! -d $OPENSHIFT_DATA_DIR/victims-web ]; then
		git clone git://github.com/victims/victims-web.git $OPENSHIFT_DATA_DIR/victims-web
		fixcfg
	fi
	(cd $OPENSHIFT_DATA_DIR/victims-web && git pull --rebase)
	ln -sf $OPENSHIFT_DATA_DIR/victims-web/src/victims_web $OPENSHIFT_REPO_DIR/libs/.
	ln -sf $OPENSHIFT_DATA_DIR/victims-web/src/victims_web/blueprints/ui/static $OPENSHIFT_REPO_DIR/wsgi/.
fi

PYDIR=$(find $OPENSHIFT_HOMEDIR -maxdepth 1 -type d -name "python*" | sort | tail -n 1)
if [ -f $PYDIR/virtenv/bin/activate ]; then
	source $PYDIR/virtenv/bin/activate
	if type -p pip > /dev/null; then
		pip install --use-mirrors -e $OPENSHIFT_DATA_DIR/victims-web
	fi
fi
