#!/bin/bash
if [ ! -d $OPENSHIFT_REPO_DIR/libs/victims_web ]; then
	if [ ! -d $OPENSHIFT_DATA_DIR/victims-web ]; then
		git clone git://github.com/victims/victims-web.git $OPENSHIFT_DATA_DIR/victims-web
	fi
	cp -r $OPENSHIFT_DATA_DIR/victims-web/src/victims_web $OPENSHIFT_REPO_DIR/libs/.
fi

PYDIR=$(find $OPENSHIFT_HOMEDIR -maxdepth 1 -type d -name "python*" | sort | tail -n 1)
if [ -f $PYDIR/virtenv/bin/activate ]; then
	source $PYDIR/virtenv/bin/activate
	if type -p pip > /dev/null; then
		pip install --use-mirrors -e $OPENSHIFT_DATA_DIR/victims-web
	fi
fi
