#!/usr/bin/python
import os
import sys

PY_VERSION = '%d.%d'%(sys.version_info[0], sys.version_info[1])
PY_DIR = 'python-%s'%(PY_VERSION)

# source: https://github.com/openshift/flask-example
sys.path.insert(0, os.path.dirname(__file__) or '.')

if os.path.exists(os.path.join(os.environ['OPENSHIFT_HOMEDIR'], PY_DIR)):
    PY_DIR = os.path.join(os.environ['OPENSHIFT_HOMEDIR'], PY_DIR)
else:
    PY_DIR = os.path.join(os.environ['OPENSHIFT_HOMEDIR'], 'python')

virtenv = PY_DIR + '/virtenv/'

PY_CACHE = os.path.join(virtenv, 'lib', PY_VERSION, 'site-packages')

os.environ['PYTHON_EGG_CACHE'] = os.path.join(PY_CACHE)
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

sys.path.insert(0, os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'victims-web', 'src'))
from victims_web import application as application

