#!/usr/bin/python
import os
import sys

PY_VERSION = '%d.%d'%(sys.version_info[0], sys.version_info[1])

sys.path.insert(0, os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'victims-web', 'src'))
from victims_web import application as application

